***
# Final Project - PFDA 2024/2025
***
### Objetive: 
Write a Nootebook that demonstrate that you, can perform data analysis on some data. I will allow a lot of flexibility in this project, so that you can use it as an opportunity to do something thta is usefull for your work.
***
##### Steps:
1. StationDetail.csv was used as data base for this project;
1. Clean and normalise the data before doing analysis;
1. Questions we can ask:
    - How much wind power is there at a particular location? 
        - This is quite open ended, is this just the mean wind speed for an hour/day/month/year, or should you take into account that there are wind ranges that the windfarms can operate in (min max speeds). 
        - Some analysis of what power when would be useful (time of day/year) 
        - Are the wind speeds likely to be the same in 10 years in the future? ie is there a trend in recorded wind speeds over the last few decades. 
        - Is there any other weather metric worth analyzing (eg rain, temp).
        - What will the power output of the windfarms in Ireland be like next week, according to the weather forecasts? (ok that is a tricky one, because you would need to get, or make up, information about the size and locations of the wind farms in Ireland, one find/makeup the windspeed to power output equation). 
        - Anything else you can think of?
***

## Step 1: Load the Data

In [27]:
import os

# Check the current working directory
print("Current working directory:", os.getcwd())

# List the files in the current directory
print("Files in the current directory:", os.listdir())

Current working directory: c:\Users\gusgo\OneDrive - Atlantic TU\PFDA\project
Files in the current directory: ['project.ipynb', 'project.py', 'StationDetail.csv']

In [28]:
import pandas as pd

# Define the file path
file_path = 'StationDetail.csv'

In [29]:
# Try to load the data
try:
    df = pd.read_csv(file_path)
    print("File loaded successfully.")
    # Display the first few rows of the dataframe
    display(df.head())
except FileNotFoundError:
    print(f"File not found: {file_path}")
except pd.errors.EmptyDataError:
    print(f"No data: {file_path}")
except pd.errors.ParserError:
    print(f"Parsing error: {file_path}")
except Exception as e:
    print(f"An error occurred: {e}")

File loaded successfully.

,county,station name,name,height(m),easting,northing,latitude,longitude,open year,close year
0,Antrim,5880,LH_RATHLIN_WEST,10,309200,451800,55.30083,-6.28028,2000,(null)
1,Carlow,4415,TULLOW (Waterworks),76,284700,173400,52.80528,-6.74306,1985,(null)
2,Carlow,2414,BORRIS G.S.,85,272400,150700,52.60278,-6.93056,1944,1991
3,Carlow,1214,CARLOW (SUGAR FACTORY),58,272200,178400,52.85139,-6.92778,1953,1960
4,Carlow,115,HACKETSTOWN RECTORY,182,297600,180500,52.86667,-6.55000,1910,1944

## Step 2: Clean and Normalize the Data

In [30]:
import pandas as pd

# Load the data

weatherdata = pd.read_csv('StationDetail.csv', delimiter=',')  # read the data from the csv file

# Display the first few rows of the dataframe
weatherdata.head()

,county,station name,name,height(m),easting,northing,latitude,longitude,open year,close year
0,Antrim,5880,LH_RATHLIN_WEST,10,309200,451800,55.30083,-6.28028,2000,(null)
1,Carlow,4415,TULLOW (Waterworks),76,284700,173400,52.80528,-6.74306,1985,(null)
2,Carlow,2414,BORRIS G.S.,85,272400,150700,52.60278,-6.93056,1944,1991
3,Carlow,1214,CARLOW (SUGAR FACTORY),58,272200,178400,52.85139,-6.92778,1953,1960
4,Carlow,115,HACKETSTOWN RECTORY,182,297600,180500,52.86667,-6.55000,1910,1944

In [31]:
weatherdata = weatherdata.rename(columns={
    'county': 'County',
    'station name': 'Station Number',
    'name': 'Station Name',
    'height(m)': 'Height(m)',
    'easting': 'Easting',
    'northing': 'Northing',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'open year': 'Open Year',
    'close year': 'Close Year'
})
weatherdata.head()

,County,Station Number,Station Name,Height(m),Easting,Northing,Latitude,Longitude,Open Year,Close Year
0,Antrim,5880,LH_RATHLIN_WEST,10,309200,451800,55.30083,-6.28028,2000,(null)
1,Carlow,4415,TULLOW (Waterworks),76,284700,173400,52.80528,-6.74306,1985,(null)
2,Carlow,2414,BORRIS G.S.,85,272400,150700,52.60278,-6.93056,1944,1991
3,Carlow,1214,CARLOW (SUGAR FACTORY),58,272200,178400,52.85139,-6.92778,1953,1960
4,Carlow,115,HACKETSTOWN RECTORY,182,297600,180500,52.86667,-6.55000,1910,1944

In [32]:
# Check for missing values
print("Missing values per column:")
print(weatherdata.isnull().sum())

# Check for duplicates
print("Number of duplicate rows:")
print(weatherdata.duplicated().sum())

# Check data types
print("Data types of columns:")
print(weatherdata.dtypes)

Missing values per column:
County            0
Station Number    0
Station Name      0
Height(m)         0
Easting           0
Northing          0
Latitude          0
Longitude         0
Open Year         0
Close Year        0
dtype: int64
Number of duplicate rows:
0
Data types of columns:
County             object
Station Number      int64
Station Name       object
Height(m)           int64
Easting             int64
Northing            int64
Latitude          float64
Longitude         float64
Open Year          object
Close Year         object
dtype: object

## Step 3: Analyze Height(m)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Mean wind speed
mean_height = weatherdata['Height(m)'].mean()
print(f"Mean wind speed: {mean_wind_speed:.2f} m/s")

# Wind speed ranges
min_operational_speed = 3.0  # Example minimum operational speed in m/s
max_operational_speed = 25.0  # Example maximum operational speed in m/s
operational_wind_speeds = weatherdata[(weatherdata['Height(m)'] >= min_operational_speed) & (df['wind_speed'] <= max_operational_speed)]
print(f"Percentage of time wind speeds are within operational range: {len(operational_wind_speeds) / len(df) * 100:.2f}%")

# Wind speed trends over time
weatherdata['date'] = pd.to_datetime(weatherdata['date'])
weatherdata.set_index('date', inplace=True)
monthly_mean_wind_speed = weatherdata['Height(m)'].resample('M').mean()

plt.figure(figsize=(12, 6))
monthly_mean_wind_speed.plot()
plt.title('Monthly Mean Wind Speed Over Time')
plt.xlabel('Date')
plt.ylabel('Wind Speed (m/s)')
plt.show()

# Wind speed trends over decades
weatherdata['year'] = weatherdata.index.year
annual_mean_wind_speed = weatherdata.groupby('year')['wind_speed'].mean()

plt.figure(figsize=(12, 6))
annual_mean_wind_speed.plot()
plt.title('Annual Mean Wind Speed Over Decades')
plt.xlabel('Year')
plt.ylabel('Wind Speed (m/s)')
plt.show()

Mean wind speed: 88.02 m/s

KeyError: 'wind_speed'